version: '3'
services:
  servigest-frontend:
    build: servigest-frontend/.
    container_name: servigest-frontend
    ports:
      - "80:80"
    depends_on:
      - servigest-backend

  servigest-backend:
    build: servigest-backend/.
    container_name: servigest-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://servigest-db:3306/servigest?serverTimezone=UTC
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - servigest-db

  servigest-db:
    image: mysql:5.7
    container_name: servigest-db
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: servigest
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: 
      # MYSQL_PASSWORD: 